
version: 2

models:
  - name: snowflake_customer_purchases
    description: "The total purchases of each customer"
    columns:
      - name: c_custkey
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: cumulative_orders_by_date
    description: "The cumulative orders by date"