
version: 2

models:
  - name: snowflake_customer_purchases
    description: "The total purchases of each customer"
    columns:
      - name: c_custkey
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: cumulative_orders_by_date
    description: "The cumulative orders by date"

  - name: datesIncremental
    description: "dates table as incremental table"
  
  - name: ephemeral_model_dbt
    description: "The first dbt table as ephemeral"

  - name: second_dbt_table
    description: "The second dbt table that refs ephemeral"

  - name: t_time
    description: "The second dbt table that use incremental"